apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
  namespace: eztio
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
      - configmaps
      - endpoints
      - events
      - namespaces
      - services

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: eztio

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  namespace: eztio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
subjects:
  - namespace: eztio
    kind: ServiceAccount
    name: prometheus