apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: eztio
spec:
  selector:
    # это label если что, а не просто name.
    name: prometheus-pod
  ports:
    - name: prometheus-svc-port
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort