apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: eztio
  annotations:
    prometheus.io.path: /stats/prometheus
    prometheus.io.port: '15020'
    prometheus.io.scrape: 'true'
spec:
  type: LoadBalancer
  selector:
    istio: ingressgateway
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 8081
      name: http-8081