server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - metric

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/eztio
    password: ${DB_PASS}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true